In [1]:
import cv2 
import numpy as np  

cap = cv2.imread('birdgrid_without_Label.jpg')
#You're free to do a resize or not, just for the example
cap = cv2.resize(cap, (340,480))
for x in range (0,340,1):
    for y in range(0,480,1):
        color = cap[y,x]
        print (color)

[ 0 15  0]
[11 36 11]
[10 34  9]
[11 30 11]
[12 27 12]
[12 32 10]
[ 9 37  8]
[ 9 36  9]
[10 31 11]
[11 30 12]
[11 31 11]
[10 31 11]
[10 31 11]
[10 32 11]
[10 35  9]
[10 31 10]
[10 33 11]
[10 31 10]
[11 32 12]
[10 31 10]
[10 34 11]
[11 32 11]
[10 32 11]
[10 32 10]
[10 32 10]
[11 32 11]
[10 32 11]
[10 33 10]
[10 32 10]
[10 32 10]
[10 32 10]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[11 31 11]
[11 32 11]
[10 32 10]
[10 32 10]
[11 32 11]
[10 32 11]
[11 32 11]
[10 32 10]
[ 5 54  5]
[ 8 41  8]
[13 23 14]
[14 23 13]
[10 33 10]
[ 9 37  8]
[10 31 10]
[11 29 11]
[10 31 11]
[10 34 10]
[11 33 10]
[11 33 10]
[10 34 10]
[10 34 10]
[10 32 11]
[11 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]
[10 31 11]